 CREATE TABLE `jobstaging` (
  `company` text COLLATE utf8mb4_general_ci,
  `jobdescription` text COLLATE utf8mb4_general_ci,
  `joblocation_address` text COLLATE utf8mb4_general_ci,
  `jobtitle` text COLLATE utf8mb4_general_ci,
  `skills1` text COLLATE utf8mb4_general_ci,
  `skills2` text COLLATE utf8mb4_general_ci,
  `skills3` text COLLATE utf8mb4_general_ci,
  `skills4` text COLLATE utf8mb4_general_ci,
  `skills5` text COLLATE utf8mb4_general_ci,
  `skills6` text COLLATE utf8mb4_general_ci,
  `skills7` text COLLATE utf8mb4_general_ci,
  `skills 1 8` text COLLATE utf8mb4_general_ci,
  `skills 1 9` text COLLATE utf8mb4_general_ci,
  `skills 1 10` text COLLATE utf8mb4_general_ci,
  `skills 1 11` text COLLATE utf8mb4_general_ci,
  `skills 1 12` text COLLATE utf8mb4_general_ci,
  `skills 1 13` text COLLATE utf8mb4_general_ci,
  `skills 1 14` text COLLATE utf8mb4_general_ci,
  `skills 1 15` text COLLATE utf8mb4_general_ci,
  `skills 1 16` text COLLATE utf8mb4_general_ci,
  `skills 1 17` text COLLATE utf8mb4_general_ci,
  `skills 1 18` text COLLATE utf8mb4_general_ci,
  `skills 1 19` text COLLATE utf8mb4_general_ci,
  `skills 1 20` text COLLATE utf8mb4_general_ci,
  `skills 1 21` text COLLATE utf8mb4_general_ci,
  `skills 1 22` text COLLATE utf8mb4_general_ci,
  `skills 1 23` text COLLATE utf8mb4_general_ci,
  `skills 1 24` text COLLATE utf8mb4_general_ci,
  `skills 1 25` text COLLATE utf8mb4_general_ci,
  `skills 1 26` text COLLATE utf8mb4_general_ci,
  `skills 1 27` text COLLATE utf8mb4_general_ci,
  `skills 1 28` text COLLATE utf8mb4_general_ci,
  `skills 2 1` text COLLATE utf8mb4_general_ci,
  `skills 2 2` text COLLATE utf8mb4_general_ci,
  `skills 2 3` text COLLATE utf8mb4_general_ci,
  `skills 2 4` text COLLATE utf8mb4_general_ci,
  `skills 2 5` text COLLATE utf8mb4_general_ci,
  `skills 2 6` text COLLATE utf8mb4_general_ci,
  `skills 2 7` text COLLATE utf8mb4_general_ci,
  `skills 2 8` text COLLATE utf8mb4_general_ci,
  `skills 2 9` text COLLATE utf8mb4_general_ci,
  `skills 2 10` text COLLATE utf8mb4_general_ci,
  `skills 2 11` text COLLATE utf8mb4_general_ci,
  `skills 2 12` text COLLATE utf8mb4_general_ci,
  `skills 2 13` text COLLATE utf8mb4_general_ci,
  `skills 3 1` text COLLATE utf8mb4_general_ci,
  `skills 3 2` text COLLATE utf8mb4_general_ci,
  `skills 3 3` text COLLATE utf8mb4_general_ci,
  `skills 3 4` text COLLATE utf8mb4_general_ci,
  `skills 3 5` text COLLATE utf8mb4_general_ci,
  `skills 4 1` text COLLATE utf8mb4_general_ci,
  `skills 4 2` text COLLATE utf8mb4_general_ci,
  `skills 4 3` text COLLATE utf8mb4_general_ci,
  `skills 4 4` text COLLATE utf8mb4_general_ci,
  `skills 4 5` text COLLATE utf8mb4_general_ci,
  `skills 4 6` text COLLATE utf8mb4_general_ci,
  `skills 5 1` text COLLATE utf8mb4_general_ci,
  `skills 5 2` text COLLATE utf8mb4_general_ci,
  `skills 5 3` text COLLATE utf8mb4_general_ci,
  `skills 5 4` text COLLATE utf8mb4_general_ci,
  `skills 5 5` text COLLATE utf8mb4_general_ci,
  `skills 5 6` text COLLATE utf8mb4_general_ci,
  `skills 6 1` text COLLATE utf8mb4_general_ci,
  `skills 6 2` text COLLATE utf8mb4_general_ci,
  `skills 6 3` text COLLATE utf8mb4_general_ci,
  `skills 6 4` text COLLATE utf8mb4_general_ci,
  `skills 6 5` text COLLATE utf8mb4_general_ci,
  `skills 7` text COLLATE utf8mb4_general_ci,
  `skills 8` text COLLATE utf8mb4_general_ci,
  `skills 9` text COLLATE utf8mb4_general_ci,
  `skills 10` text COLLATE utf8mb4_general_ci,
  `skills 11` text COLLATE utf8mb4_general_ci,
  `skills 12` text COLLATE utf8mb4_general_ci,
  `skills 13` text COLLATE utf8mb4_general_ci,
  `skills 14` text COLLATE utf8mb4_general_ci,
  `skills 15` text COLLATE utf8mb4_general_ci,
  `skills 16` text COLLATE utf8mb4_general_ci,
  `skills 17` text COLLATE utf8mb4_general_ci,
  `skills 18` text COLLATE utf8mb4_general_ci,
  `skills 19` text COLLATE utf8mb4_general_ci,
  `skills 20` text COLLATE utf8mb4_general_ci,
  `skills 21` text COLLATE utf8mb4_general_ci,
  `skills 22` text COLLATE utf8mb4_general_ci,
  `skills 23` text COLLATE utf8mb4_general_ci,
  `skills 24` text COLLATE utf8mb4_general_ci,
  `skills 25` text COLLATE utf8mb4_general_ci,
  `skills 26` text COLLATE utf8mb4_general_ci,
  `skills 27` text COLLATE utf8mb4_general_ci,
  `skills 28` text COLLATE utf8mb4_general_ci,
  `skills 29` text COLLATE utf8mb4_general_ci,
  `skills 30` text COLLATE utf8mb4_general_ci,
  `skills 31` text COLLATE utf8mb4_general_ci,
  `skills 32` text COLLATE utf8mb4_general_ci,
  `skills 33` text COLLATE utf8mb4_general_ci,
  `skills 34` text COLLATE utf8mb4_general_ci,
  `skills 35` text COLLATE utf8mb4_general_ci,
  `skills 36` text COLLATE utf8mb4_general_ci,
  `skills 37` text COLLATE utf8mb4_general_ci,
  `skills 38` text COLLATE utf8mb4_general_ci,
  `skills 39` text COLLATE utf8mb4_general_ci,
  `skills 40` text COLLATE utf8mb4_general_ci,
  `skills 41` text COLLATE utf8mb4_general_ci,
  `skills 42` text COLLATE utf8mb4_general_ci,
  `skills 43` text COLLATE utf8mb4_general_ci,
  `skills 44` text COLLATE utf8mb4_general_ci,
  `skills 45` text COLLATE utf8mb4_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

